trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      project: AzurePlatform
      trigger:
        stages:
          - listCommitsSinceLastRelease
        branches:
          - master
stages:
  - stage: Stage1
    displayName: Print
    dependsOn: []
    jobs:
      - job: Print
        displayName: Print
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "environmentName: '$(environmentName)'"
              echo "environmentCategory": '$(environmentCategory)'
              echo "applicationCode": '$(applicationCode)'
              echo "applicationShortCode": '$(applicationShortCode)'
              
              
            displayName: Print